name = "entreprise"
version = "1.0.0"

description = "Expenses tracker made for learning purposes."

[dependencies]
gleam_stdlib = "~> 0.36 or ~> 1.0"
lustre = "~> 4.0"
mist = "~> 1.0"
gleam_erlang = "~> 0.25"
gleam_otp = "~> 0.10"
gleam_http = "~> 3.6"
lustre_ui = "~> 0.5"
gleam_json = "~> 1.0"
simplifile = "~> 1.6"
sqlight = "~> 0.9"
lustre_http = "~> 0.5"

[dev-dependencies]
gleeunit = "~> 1.0"
